BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Volunteers" (
	"VolunteerID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	PRIMARY KEY("VolunteerID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Assignments" (
	"VolunteerID"	INTEGER NOT NULL,
	"ShiftID"	INTEGER NOT NULL,
	FOREIGN KEY("VolunteerID") REFERENCES "Volunteers"("VolunteerID"),
	FOREIGN KEY("ShiftID") REFERENCES "Shifts"
);
CREATE TABLE IF NOT EXISTS "Shifts" (
	"ShiftID"	INTEGER NOT NULL UNIQUE,
	"Start_time"	TEXT NOT NULL,
	"End_time"	TEXT NOT NULL,
	PRIMARY KEY("ShiftID" AUTOINCREMENT)
);
COMMIT;
